-- DDL generated by Postico 1.5.21
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE messages (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX messages_pkey ON messages(id int4_ops);
